#!/bin/bash


# first line will define the interpreter

# Simple note-taking script
# Author: reindert


# get the date this note was posted
declare -r date=$(date)

#get the topic
declare -r topic="$1"

# We can set the $NOTESDIR variable in the bashrc file and export it
# so that it can be picked up here . otherwise it takes its default.
# eg) export NOTESDIR="${HOME}/notes"
# When bash starts, it reads from .bashrc file. So they will be available
# to all subprocess files.

#filename to write to
#declare notesdir="${HOME}/Desktop/bashDemo/tn-notes"
#[[ $NOTESDIR ]] && notesdir="${NOTESDIR}"

declare notesdir="${NOTESDIR:-${HOME}/Desktop/bashDemo/tn-notes}"

if [[ ! -d $notesdir ]]; then
    mkdir -- "${notesdir}" 2>/dev/null || { echo "Cannot make directory ${notesdir}" 1>&2; exit 1; }
fi

# filename to write to
declare -r filename="${notesdir}/${topic}notes.txt"

# Does file exist? If not, create it
if [[ ! -f $filename ]]; then
    touch -- "${filename}" 2>/dev/null || { echo "Cannot create file ${filename}" 1>&2; exit 1; }
fi

#Is file writeable?
[[ -w $filename ]] || { echo "${filename} is not writeable" 1>&2; exit 1; }

# Ask user for input
read -p "Your note: " note

if [[ $note ]]; then
    echo "$date: $note" >> "$filename"
    echo "Note '$note' saved to $filename"
else
    "No input. Note wasn't saved"
fi
